exports.run = async (client, message, args) => {
    message.delete();
    var util = require("../fivem");
    let embed = new Discord.RichEmbed()
    .setAuthor(state, client.user.avatarURL)
    .setColor(color)
    .setDescription(`**Bot Help**`)
    .addField(`Servidores de VandalRP` , "Servidor de RP - https://discord.gg/Wx3n94p7WZ Servidor de trabajos publicos - https://discord.gg/j5kracjVAw")
    .addBlankField(true)
    .addField(`${config.prefix}players`, "Te muestra la gente online del servidor")
    .addField(`${config.prefix}server`, "Te muestra toda la informacion del servidor")
    .addField(`${config.prefix}find <username>`, "Encuentra a una persona dentro del server")
    .addField(`${config.prefix}id <id>`, "Encuentra un usuario que está en el servidor a través del ID del servidor")
    .addField(`${config.prefix}status`, "Comprueba si el servidor está en línea")
    .addField(`${config.prefix}stats`, "Comprueba las estadísticas del bot")
    .addField(`${config.prefix}save-log <person's server id>`, "Guarda la información de un jugador")
    .addField(`${config.prefix}get-log`, "Obtiene la información de un jugador (por rango)")
    .addField(`${config.prefix}forum <topic>`, "Busca los temas más recientes en las categorías de https://forum.fivem.net")
    .addField(`${config.prefix}forum `, "Comprueba las categorías actuales en https://forum.fivem.net")
    .addField(`${config.prefix}forum search <search terms>`, "Busca términos en https://forum.fivem.net")
    .addField(`${config.prefix}forum user <username>`, "Busca la información del usuario en https://forum.fivem.net")
    .addField(`${config.prefix}cache`, "Te enseña a como borrar caché facilmente")
    .addField(`${config.prefix}ip`, "Muestra cual es la ip actual del servidor y como poder entrar a el")
    .addBlankField(true)
    .setThumbnail(icon)
    .setTitle("VandalRP")
    .setURL("https://discord.gg/Wx3n94p7WZ")
    .addBlankField(true)
    .addField("Para donar pulsa en donar aquí:", "[Donar](https://www.paypal.com/donate?hosted_button_id=G8QLU3PKWQX5A)")
    .addBlankField(true)
    .addField("", news)
    .setFooter("VandalRP", client.user.avatarURL)
    log(`Fivem help cmd was used.. in ${message.guild.name}`)
  
    message.channel.send({embed: embed})
};